//! Load and launch ahead-of-time compiled Triton kernels from Rust.
//!
//! The Triton fusion arm must run under the same driver as every other arm, or
//! the benchmark measures language runtime instead of kernel time. Triton
//! exposes its compiled cubin, so `tools/triton_aot.py` emits `.cubin` plus a
//! manifest at build time and this crate launches it through the CUDA driver
//! API. Python is never in the measured path.
//!
//! ## The launch ABI
//!
//! Undocumented; read out of `triton/backends/nvidia/driver.py` in Triton 3.6.0
//! and validated end to end by `validate_abi`:
//!
//! * Kernel params are the non-constexpr arguments in declaration order,
//!   followed by `global_scratch` then `profile_scratch` (driver.py:261-262).
//!   Both are `CUdeviceptr`, null when their sizes are zero. **Omitting them
//!   does not fail the launch**, it reads garbage from the param space.
//! * `blockDimX = 32 * num_warps` (driver.py:330). This is NOT the `BLOCK`
//!   constexpr. `BLOCK` is a tile size; confusing them launches the wrong
//!   shape and silently computes the wrong answer.
//! * `shared` from the manifest is dynamic shared memory.
//!
//! Every one of those fails *silently* rather than loudly, which is why
//! `validate_abi` checks numerical output against Python-launched reference
//! values rather than merely checking that the launch returned success.
//!
//! Raw driver FFI rather than a crate: the surface needed is small, and the
//! project already depends on the CUDA toolchain.

use std::ffi::{c_void, CString};
use std::path::Path;

pub use cuda_min::{check, CuError, CudaContext, CUdeviceptr, DeviceBuffer};
use cuda_min::{cuLaunchKernel, cuModuleGetFunction, cuModuleLoadData, cuModuleUnload, CUfunction, CUmodule};

/// The subset of the AOT manifest the launcher needs.
#[derive(Debug, Clone)]
pub struct Manifest {
    pub name: String,
    pub num_warps: u32,
    pub block_dim_x: u32,
    pub shared_bytes: u32,
    pub global_scratch_size: usize,
    pub profile_scratch_size: usize,
    pub runtime_args: Vec<String>,
}

impl Manifest {
    /// Minimal field extraction. Deliberately dependency-free: pulling in a
    /// JSON crate for six fields is not worth the build-time cost, and the
    /// manifest is generated by our own tool so its shape is fixed.
    pub fn from_json(path: &Path) -> Result<Self, CuError> {
        let text = std::fs::read_to_string(path).map_err(|e| CuError::Io {
            path: path.display().to_string(),
            source: e,
        })?;
        let p = path.display().to_string();
        let err = |msg: String| CuError::Manifest {
            path: p.clone(),
            msg,
        };

        let str_field = |key: &str| -> Result<String, CuError> {
            let pat = format!("\"{key}\":");
            let i = text.find(&pat).ok_or_else(|| err(format!("missing {key}")))?;
            let rest = &text[i + pat.len()..];
            let a = rest.find('"').ok_or_else(|| err(format!("bad {key}")))?;
            let b = rest[a + 1..]
                .find('"')
                .ok_or_else(|| err(format!("bad {key}")))?;
            Ok(rest[a + 1..a + 1 + b].to_string())
        };
        let num_field = |key: &str| -> Result<u64, CuError> {
            let pat = format!("\"{key}\":");
            let i = text.find(&pat).ok_or_else(|| err(format!("missing {key}")))?;
            let rest = text[i + pat.len()..].trim_start();
            let end = rest
                .find(|c: char| !c.is_ascii_digit())
                .unwrap_or(rest.len());
            rest[..end]
                .parse::<u64>()
                .map_err(|_| err(format!("bad number for {key}")))
        };

        // Argument names, in declaration order. Order is the ABI.
        let mut runtime_args = Vec::new();
        if let Some(i) = text.find("\"runtime_args\":") {
            let seg = &text[i..];
            let end = seg.find(']').unwrap_or(seg.len());
            for chunk in seg[..end].split("\"name\":").skip(1) {
                let rest = chunk.trim_start();
                if let Some(a) = rest.find('"') {
                    if let Some(b) = rest[a + 1..].find('"') {
                        runtime_args.push(rest[a + 1..a + 1 + b].to_string());
                    }
                }
            }
        }

        Ok(Manifest {
            name: str_field("name")?,
            num_warps: num_field("num_warps")? as u32,
            block_dim_x: num_field("block_dim_x")? as u32,
            shared_bytes: num_field("shared_bytes")? as u32,
            global_scratch_size: num_field("global_scratch_size")? as usize,
            profile_scratch_size: num_field("profile_scratch_size")? as usize,
            runtime_args,
        })
    }
}

/// One AOT-compiled Triton kernel, ready to launch.
pub struct TritonKernel {
    module: CUmodule,
    func: CUfunction,
    pub manifest: Manifest,
    // Scratch buffers the launcher passes as the two trailing params. Held so
    // their lifetime covers every launch.
    _global_scratch: Option<DeviceBuffer>,
    _profile_scratch: Option<DeviceBuffer>,
    global_scratch_ptr: CUdeviceptr,
    profile_scratch_ptr: CUdeviceptr,
}

impl TritonKernel {
    /// Load `<dir>/<name>.cubin` with `<dir>/<name>.json`.
    pub fn load(dir: &Path, name: &str) -> Result<Self, CuError> {
        let manifest = Manifest::from_json(&dir.join(format!("{name}.json")))?;
        let cubin_path = dir.join(format!("{name}.cubin"));
        let cubin = std::fs::read(&cubin_path).map_err(|e| CuError::Io {
            path: cubin_path.display().to_string(),
            source: e,
        })?;

        // SAFETY: `cubin` outlives the call; cuModuleLoadData copies the image.
        let module = unsafe {
            let mut m: CUmodule = std::ptr::null_mut();
            check(
                "cuModuleLoadData",
                cuModuleLoadData(&mut m, cubin.as_ptr() as *const c_void),
            )?;
            m
        };

        let cname = CString::new(manifest.name.as_str()).unwrap();
        // SAFETY: module is live; the name comes from the manifest the same
        // build step emitted, so it matches the cubin's entry symbol.
        let func = unsafe {
            let mut f: CUfunction = std::ptr::null_mut();
            check(
                "cuModuleGetFunction",
                cuModuleGetFunction(&mut f, module, cname.as_ptr()),
            )?;
            f
        };

        // Allocate the trailing scratch buffers only when non-zero. A null
        // pointer is what the Python launcher passes in that case.
        let g = if manifest.global_scratch_size > 0 {
            Some(DeviceBuffer::zeroed(manifest.global_scratch_size)?)
        } else {
            None
        };
        let p = if manifest.profile_scratch_size > 0 {
            Some(DeviceBuffer::zeroed(manifest.profile_scratch_size)?)
        } else {
            None
        };
        let gp = g.as_ref().map(|b| b.ptr()).unwrap_or(0);
        let pp = p.as_ref().map(|b| b.ptr()).unwrap_or(0);

        Ok(Self {
            module,
            func,
            manifest,
            _global_scratch: g,
            _profile_scratch: p,
            global_scratch_ptr: gp,
            profile_scratch_ptr: pp,
        })
    }

    /// Launch with `args` as the runtime (non-constexpr) parameters.
    ///
    /// The two trailing scratch pointers are appended here, so callers pass
    /// only the kernel's own arguments and cannot forget them.
    ///
    /// # Safety
    /// Each entry of `args` must point to a live value whose type matches the
    /// kernel's declared parameter type, and device pointers must address
    /// allocations large enough for the kernel's accesses. Neither is checked.
    pub unsafe fn launch(&self, grid_x: u32, args: &mut [*mut c_void]) -> Result<(), CuError> {
        let mut params: Vec<*mut c_void> = Vec::with_capacity(args.len() + 2);
        params.extend_from_slice(args);
        // driver.py:261-262. Order matters and omission is silent.
        params.push(&self.global_scratch_ptr as *const _ as *mut c_void);
        params.push(&self.profile_scratch_ptr as *const _ as *mut c_void);

        check(
            "cuLaunchKernel",
            cuLaunchKernel(
                self.func,
                grid_x,
                1,
                1,
                self.manifest.block_dim_x, // 32 * num_warps, NOT the BLOCK constexpr
                1,
                1,
                self.manifest.shared_bytes,
                std::ptr::null_mut(),
                params.as_mut_ptr(),
                std::ptr::null_mut(),
            ),
        )
    }
}

impl Drop for TritonKernel {
    fn drop(&mut self) {
        if !self.module.is_null() {
            // SAFETY: loaded by cuModuleLoadData, unloaded once.
            unsafe { cuModuleUnload(self.module) };
            self.module = std::ptr::null_mut();
        }
    }
}
