"""AOT-compile the TSDF Triton kernels (arms A5a/A5b) to cubin + a C manifest.

Companion to tools/triton_aot.py, which does the same for the S2 spike kernels.
See docs/TRITON-ABI.md for the launch contract; the short version is that the
parameter list is the non-constexpr arguments in declaration order followed by
`global_scratch` then `profile_scratch`, and blockDimX is 32 * num_warps rather
than the BLOCK constexpr.

Emits a C header rather than JSON because the consumer is the C++ cross-check.
Parsing JSON there would add a dependency to read six integers that this script
already knows.

Usage: python tools/triton_aot_tsdf.py [outdir]
"""

from __future__ import annotations

import pathlib
import sys

import torch
import triton

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "triton"))
import tsdf_kernels as K  # noqa: E402

# Must match the C++ volume. Compiled in as constexprs, so a change here needs a
# recompile, not just a different launch argument.
BLOCK = 256
STEPS = 4          # ceil(trunc / voxel) with the default trunc = 4 * voxel
MAX_PROBE = 8
BLOCK_DIM = 8
BLOCK_VOXELS = 512


def main(argv: list[str]) -> int:
    outdir = pathlib.Path(argv[1] if len(argv) > 1 else REPO / "artifacts" / "triton")
    outdir.mkdir(parents=True, exist_ok=True)

    dev = "cuda"
    hash_size, pool = 1 << 15, 1 << 14
    t64 = torch.full((hash_size * 2,), -1, dtype=torch.int64, device=dev)
    t32 = t64.view(torch.int32)
    bc = torch.zeros(1, dtype=torch.int32, device=dev)
    bco = torch.zeros(pool * 3, dtype=torch.int32, device=dev)
    dr = torch.zeros(1, dtype=torch.int64, device=dev)
    tsdf = torch.zeros(pool * BLOCK_VOXELS, dtype=torch.float32, device=dev)
    w = torch.zeros(pool * BLOCK_VOXELS, dtype=torch.float32, device=dev)
    pos = torch.zeros(1024 * 3, dtype=torch.float32, device=dev)

    pass

    cx = dict(BLOCK=BLOCK, STEPS=STEPS, MAX_PROBE=MAX_PROBE, BLOCK_DIM=BLOCK_DIM)

    k_alloc = K.tsdf_alloc_kernel[(4,)](
        pos, t64, t32, bc, bco, dr, hash_size, 1024, hash_size - 1, pool,
        0.01, 0.04, 0.0, 0.0, 0.0, 0.0, **cx)
    k_update = K.tsdf_update_kernel[(4,)](
        pos, t64, t32, tsdf, w, w, w, w, 1024, hash_size - 1,
        0.01, 0.04, 32.0, 0.0, 0.0, 0.0, 0.0, BLOCK_VOXELS=BLOCK_VOXELS, **cx)

    lines = [
        "// Generated by tools/triton_aot_tsdf.py. Do not edit.",
        "//",
        "// Launch constants for the AOT-compiled Triton TSDF kernels. blockDimX is",
        "// 32 * num_warps and is NOT the BLOCK constexpr: BLOCK is a tile size.",
        "// Confusing the two launches the wrong shape and silently computes the",
        "// wrong answer. See docs/TRITON-ABI.md.",
        "#pragma once",
        "",
        f"#define OSN_TRITON_BLOCK {BLOCK}",
        f"#define OSN_TRITON_STEPS {STEPS}",
        f"#define OSN_TRITON_MAX_PROBE {MAX_PROBE}",
        "",
    ]
    for tag, k in (("ALLOC", k_alloc), ("UPDATE", k_update)):
        md = k.metadata
        name = md.name
        (outdir / f"{name}.cubin").write_bytes(k.asm["cubin"])
        lines += [
            f'#define OSN_TRITON_{tag}_NAME "{name}"',
            f"#define OSN_TRITON_{tag}_BLOCK_DIM_X {32 * md.num_warps}",
            f"#define OSN_TRITON_{tag}_SHARED {md.shared}",
            f"#define OSN_TRITON_{tag}_GLOBAL_SCRATCH {md.global_scratch_size}",
            f"#define OSN_TRITON_{tag}_PROFILE_SCRATCH {getattr(md, 'profile_scratch_size', 0)}",
            "",
        ]
        print(f"{name}: {len(k.asm['cubin'])} bytes, blockDimX {32 * md.num_warps}, "
              f"shared {md.shared}, regs {k.n_regs}")

    (outdir / "triton_tsdf_manifest.h").write_text("\n".join(lines) + "\n")
    print(f"wrote cubins + triton_tsdf_manifest.h to {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
